import type { Comment, User } from "./types";

export const AKUN_SAYA = "u_saya";

export const PENGGUNA: Record<string, User> = {
  [AKUN_SAYA]: {
    id: AKUN_SAYA,
    name: "Rangga Mahardika",
    handle: "ranggamhd",
    bio: "Membangun produk digital di Jakarta. Menulis catatan pendek soal desain antarmuka, kualitas kode, dan kebiasaan tim yang bekerja.",
    location: "Jakarta, Indonesia",
    joinedAt: "Maret 2021",
    following: 312,
    followers: 8420,
    verified: true,
  },
  u_ayu: {
    id: "u_ayu",
    name: "Ayu Prameswari",
    handle: "ayuprames",
    bio: "Product designer.",
    location: "Bandung",
    joinedAt: "Juli 2019",
    following: 480,
    followers: 12300,
    verified: false,
  },
  u_dimas: {
    id: "u_dimas",
    name: "Dimas Anggara",
    handle: "dimsanggara",
    bio: "Backend engineer.",
    location: "Yogyakarta",
    joinedAt: "Januari 2018",
    following: 201,
    followers: 5120,
    verified: false,
  },
  u_nadia: {
    id: "u_nadia",
    name: "Nadia Rahmawati",
    handle: "nadiarhm",
    bio: "Riset pengguna.",
    location: "Surabaya",
    joinedAt: "September 2020",
    following: 356,
    followers: 2870,
    verified: true,
  },
  u_bagas: {
    id: "u_bagas",
    name: "Bagas Wicaksana",
    handle: "bagaswcks",
    bio: "Frontend engineer.",
    location: "Semarang",
    joinedAt: "Mei 2022",
    following: 128,
    followers: 940,
    verified: false,
  },
  u_sekar: {
    id: "u_sekar",
    name: "Sekar Ayuningtyas",
    handle: "sekarayu",
    bio: "Menulis soal produk.",
    location: "Denpasar",
    joinedAt: "Februari 2023",
    following: 92,
    followers: 1610,
    verified: false,
  },
};

/** Titik acuan waktu; setiap komentar disimpan sebagai selisih menit dari sekarang. */
const ACUAN = Date.now();
const menitLalu = (menit: number) => ACUAN - menit * 60 * 1000;

type Benih = Omit<Comment, "createdAt"> & { menit: number };

const BENIH: Benih[] = [
  {
    id: "k1",
    authorId: "u_ayu",
    parentId: null,
    text: "Antarmuka yang baik jarang terasa pintar. Ia terasa seperti tidak ada, sampai kamu sadar sudah selesai mengerjakan sesuatu.",
    menit: 9,
    likes: 1284,
    reposts: 96,
    liked: true,
    reposted: false,
  },
  {
    id: "k2",
    authorId: AKUN_SAYA,
    parentId: "k1",
    text: "Setuju. Ukuran keberhasilan desain bukan seberapa lama orang menatapnya, tapi seberapa cepat mereka lupa sedang memakainya.",
    menit: 14,
    likes: 312,
    reposts: 21,
    liked: false,
    reposted: false,
  },
  {
    id: "k3",
    authorId: "u_dimas",
    parentId: null,
    text: "Tiga jam menelusuri bug yang ternyata cuma salah urutan dua baris. Catatan untuk diri sendiri: baca ulang kode sebelum menuduh basis datanya.",
    menit: 38,
    likes: 640,
    reposts: 44,
    liked: false,
    reposted: false,
  },
  {
    id: "k4",
    authorId: AKUN_SAYA,
    parentId: null,
    text: "Kalau sebuah fitur butuh dokumentasi tiga halaman supaya bisa dipakai, yang perlu diperbaiki biasanya bukan dokumentasinya.",
    menit: 52,
    likes: 2140,
    reposts: 318,
    liked: false,
    reposted: true,
  },
  {
    id: "k5",
    authorId: "u_nadia",
    parentId: "k4",
    text: "Dari sesi riset minggu lalu, tujuh dari sepuluh peserta tidak membuka panduan sama sekali. Mereka menebak, dan tebakannya konsisten. Itu sinyal yang bagus untuk dipakai.",
    menit: 47,
    likes: 508,
    reposts: 63,
    liked: true,
    reposted: false,
  },
  {
    id: "k6",
    authorId: "u_bagas",
    parentId: null,
    text: "Menghapus 400 baris kode hari ini tanpa mengubah satu pun perilaku aplikasi. Hari kerja paling produktif bulan ini.",
    menit: 96,
    likes: 883,
    reposts: 77,
    liked: false,
    reposted: false,
  },
  {
    id: "k7",
    authorId: AKUN_SAYA,
    parentId: "k6",
    text: "Kode yang paling murah dirawat adalah kode yang tidak pernah ditulis. Nomor duanya kode yang berani dihapus.",
    menit: 91,
    likes: 1470,
    reposts: 189,
    liked: false,
    reposted: false,
  },
  {
    id: "k8",
    authorId: "u_sekar",
    parentId: null,
    text: "Rapat yang tidak punya keputusan di akhir sebenarnya bukan rapat, melainkan pembacaan status yang mahal.",
    menit: 170,
    likes: 1912,
    reposts: 402,
    liked: true,
    reposted: false,
  },
  {
    id: "k9",
    authorId: AKUN_SAYA,
    parentId: null,
    text: "Antarmuka gelap bukan soal selera semata. Kontras yang salah tetap melelahkan mata di tema mana pun. Ukur dulu, baru pilih warnanya.",
    menit: 320,
    likes: 964,
    reposts: 121,
    liked: false,
    reposted: false,
  },
  {
    id: "k10",
    authorId: "u_ayu",
    parentId: "k9",
    text: "Rasio 4.5:1 untuk teks biasa dan 3:1 untuk teks besar. Angka yang gampang diingat, tapi entah kenapa sering jadi yang pertama dikorbankan.",
    menit: 305,
    likes: 421,
    reposts: 38,
    liked: false,
    reposted: false,
  },
  {
    id: "k11",
    authorId: "u_dimas",
    parentId: null,
    text: "Skala bukan soal server yang lebih besar, tapi soal jumlah percakapan yang harus terjadi sebelum satu keputusan bisa diambil.",
    menit: 690,
    likes: 1105,
    reposts: 233,
    liked: true,
    reposted: false,
  },
  {
    id: "k12",
    authorId: AKUN_SAYA,
    parentId: null,
    text: "Tulis catatan rilis seolah pembacanya baru bangun tidur. Kalau masih bisa dipahami, berarti sudah cukup jelas.",
    menit: 1_580,
    likes: 3260,
    reposts: 540,
    liked: false,
    reposted: false,
  },
  {
    id: "k13",
    authorId: "u_nadia",
    parentId: null,
    text: "Pengguna jarang bilang apa yang mereka mau. Mereka menunjukkan apa yang mereka hindari. Perhatikan bagian yang selalu dilewati.",
    menit: 2_950,
    likes: 2480,
    reposts: 371,
    liked: false,
    reposted: false,
  },
  {
    id: "k14",
    authorId: AKUN_SAYA,
    parentId: null,
    text: "Setelah setahun, satu-satunya kebiasaan tim yang benar-benar berpengaruh: setiap perubahan harus muat dibaca dalam satu kali duduk.",
    menit: 11_800,
    likes: 4120,
    reposts: 812,
    liked: false,
    reposted: false,
  },
];

export const KOMENTAR_AWAL: Comment[] = BENIH.map(({ menit, ...sisa }) => ({
  ...sisa,
  createdAt: menitLalu(menit),
}));
